[feat] ImageResponseSQS 리스너 기능 추가
software-maestro-starting-blue/fourtooncookie-backend pull request #160
Opened 2024-10-03 07:41 UTC by minseojo

# [feat] ImageResponseSQS 리스너 기능 추가
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-406
---
* 구현 내용
- SQS 관련 build.gradle 추가
- SQS Config 클래스 추가
- Diary 도메인에 isImageGenerationComplet() 메서드 추가
    -  4장의 이미지가 있다면, 4장의 이미지가 전부 그려졌는지 확인하는 메서드
- SQSMessageListenService 클래스 추가
    - 그림 이미지 요청에 대한 성공실패 여부를 SQS를 통해  받은 후, 적용하는 메서드
- AWS 서브넷 Ec2 2개, SQS 통신 하기 위한 VPC 엔드포인트 추가
- SQS IAM 설정

* 추가 발생한 문제(논의 사항)

2024-10-04 13:58 UTC, JuneBridge03 approved these changes
코드 잘 보았습니다!

다만, SQSListener가 너무 많은 역할을 진행하고 있고, 일부 수정과 상수화가 필요한 지점이 있어보여서 Comment로 달아드립니다.

+ 현 PR의 문제는 아니나, DiaryPaintingImageGenerationStatus의 값들의 명명이 애매한 것 같습니다.
SUCCESS -> SUCCEED, FAILURE -> FAILED
와 같이 바뀌어야 한다고는 생각하나, 추후에 논의해봅시다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/aws/sqs/SQSConfig.java
> +                        .acknowledgementInterval(Duration.ofSeconds(5))
Duration은 상수화 가능해보이기는 합니다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +        return true;
목적이 모든 이미지가 생성됨을 확인하고 싶으신것이라면 다음과 같이 코드를 정제할 수 있다고 생각합니다.
(특히, paintingImageGenerationStatus가 Generating 또는 Failure임을 따지는 것보다 Success가 아님을 따지는 것이 함수의 목적성에 더 가깝다고 생각합니다. 이미지가 전부 SUCCESS인가를 확인하는 것이 이 로직의 목표이기 때문입니다.)

```java
return paintingImageGenerationStatuses.stream()
    .noneMatch(status -> status != DiaryPaintingImageGenerationStatus.SUCCESS);
```

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/listener/DiarySQSMessageListener.java
> +    private final DiaryRepository diaryRepository;
DiaryService와 DiaryRepository가 하나의 클래스에서 다루어진다는 것은 너무 큰 부담인 듯 합니다.

차라리 DiaryRepository가 필요한 로직은 DiarySQSService와 같이 (혹은 DiaryService에) 서비스 로직으로 분리한 이후 처리하는 것이 좋다고 생각합니다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/listener/DiarySQSMessageListener.java
> +public class DiarySQSMessageListener {
전반적으로 Listener에 너무 많은 책임(SQS Message 풀링, Diary 성공/실패 처리 등)이 있는 듯 합니다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/global/authentication/filter/AuthenticationFilter.java
> +import com.startingblue.fourtooncookie.diary.listener.DiarySQSMessageListener;
굳이 필요하다고 생각하지 않습니다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/test/java/com/startingblue/fourtooncookie/diary/service/DiarySQSMessageListenServiceTest.java
> +    }
추후에 다른 테스트코드와의 로직 공통화를 위해 다른 클래스로 분리하는 것도 고려해보시면 좋을 듯 합니다.

2024-10-04 13:58 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/listener/DiarySQSMessageListener.java
> +    @SqsListener(value = "fourtooncookie_image_response_sqs.fifo", factory = "defaultSqsListenerContainerFactory")
value의 값은 상수화하여도 좋을 듯 합니다.

2024-10-04 13:58 UTC, JuneBridge03 requested changes
코멘트가 아닌 Approve로 드려서.. 혼선방지를 위해 Request Changes로 일단 드립니다.

2024-10-08 08:27 UTC, SproutMJ approved these changes
저는 일단 approve하겠습니다

2024-10-08 09:24 UTC, JuneBridge03 reviewed
리뷰 반영된 것 잘 보았습니다.

다만, 수정 로직에서 사이드이펙트가 우려되어 해당 리뷰를 하나 남겨드립니다.

2024-10-08 09:24 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +        );
DiaryStatus와 상관없이 paintingImageGenerationStatuses를 바로 모두 GENERATING으로 바꾸는 것은 추후 사이드 이펙트가 발생할 요소인 것 같습니다. (반례: DiaryStatus가 SUCCESS나 FAILED인 경우)
update의 역할을 조금 더 한정하거나 (예: updateContent, updateCharacter 등..) status에 따른 paintingImageGenerationStatuses에 대한 로직을 여러 개 추가하는 방식으로 진행하는 것이 좋을 것 같습니다.

2024-10-08 09:29 UTC, JuneBridge03 commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/domain/Diary.java
> +        );
116c8f25bbd5ca7c438de70f5c7fea139fe38c95

해당 커밋에서 반영됨을 확인하였습니다.

2024-10-08 14:23 UTC, SproutMJ commented on fourtooncookie/src/main/java/com/startingblue/fourtooncookie/diary/service/DiaryService.java
> +        if (diaryId == null) return false;
이부분은 다른 부분에서 null처리하는 방식이랑 다른거같은데 특별한 이유가 있을까요?

2024-10-14 05:01 UTC, merged