[feat] Character 도메인에 Content 필드 추가
software-maestro-starting-blue/fourtooncookie-backend pull request #198
Opened 2024-10-31 02:12 UTC by minseojo

# [feat] Character 도메인에 Content 필드 추가 
### Pull Request 타입
- [ ] bug (버그수정)
- [x] feat (기능)
- [ ] style (코드 스타일 수정)
- [ ] refactor(기능 변경 없는 수정)
- [ ] build (빌드)
- [ ] CI/CD (배포)
- [ ] doc (문서화)
- [ ] chore (간단한 수정)
- [ ] merge (병합)

### TSK-480
---
* 구현 내용
- Chracter 에 description 필드 추가
- description추가에 따른 Chracter request DTO 변경
- CharacterService addCharacter(), validateUniqueCharacter() 변경
- 테스트 코드 변경
- translation 테이블에 내용 추가 (노션 참고)

2024-10-31 10:14 UTC, SproutMJ approved these changes

2024-11-05 03:38 UTC, JuneBridge03 requested changes
수정된 부분 잘 확인하였습니다.

다만, Character와 관련한 Response DTO의 내용에도 description이 추가되는 것이 좋을 것 같다고 생각하여 request change를 드리는 바입니다.

2024-11-06 04:31 UTC, minseojo commented
> 수정된 부분 잘 확인하였습니다.
> 
> 다만, Character와 관련한 Response DTO의 내용에도 description이 추가되는 것이 좋을 것 같다고 생각하여 request change를 드리는 바입니다.

넵 프론트와 템포를 맞추려고 반영안했는데, 반영했습니다.

2024-11-07 23:46 UTC, JuneBridge03 approved these changes
반영된 부분 확인하였습니다.

2024-11-10 02:03 UTC, merged